### ISSUE TITLE
Failed emoji ZWJ sequences stick to view

### ISSUE THREAD

**Issue by luetage** [makew0rld/amfora#254] opened 2021-09-18 15:13 UTC
I’m gonna try to explain this…
I’m using Alacritty, which is unable to display emoji ZWJ sequences, instead it displays all graphemes of the sequence. This is fine, but with Amfora the additional graphemes stick and will continue to display on every page until one of the pages happens to overwrite the line and column the emoji is being displayed on. I thought maybe the view could be cleared somehow before loading a page.

Example page: <gemini://freeshell.de/gemlog/2021-09-15.gmi>

![emoji-sequence](https://user-images.githubusercontent.com/13988217/133893485-ea48d5a5-8463-4d9a-b221-954b67c9f714.png)

![emoji-sticks](https://user-images.githubusercontent.com/13988217/133893514-0229ae68-a792-4dba-b97f-a7e345286823.png)

I can reproduce this behavior on Gnome terminal.

**Comment by makeworld-the-better-one** [comment] 2021-09-18 15:55
Wow, interesting. I think I've experienced before on Guake and Tilix terminals, but dismissed it as a terminal unicode issue. I have reproduced this on Tilix just now.

Since this is appearing on all these terminals, including Alacritty which iirc is built from scratch, this must be an Amfora issue, or rather an upstream one with cview or tcell.

If I can create a small test case for this that reproduces the bug only using cview, I'll file an issue. Anyone else is welcome to try and create one as well.

**Comment by luetage** [comment] 2021-09-18 17:54
To add to this, the residual graphemes are never properly overwritten. After browsing for a while and using the scrollwheel on an almost empty page (new tab), the emoji show up multiplied.

![residual-emoji](https://user-images.githubusercontent.com/13988217/133897985-daf75fb6-3b9a-4d3a-b3c6-1110fd9ac2dc.png)

**Comment by makew0rld** [comment] 2024-12-19 01:31
I am closing this because I can't reproduce it with Wezterm and because Amfora is in maintenance mode. If this bug can still be reproduced can be fixed with a simple PR I will accept it.

Due to things working fine in Wezterm, I am suspicious that this is a terminal issue after all, and unrelated to Amfora or it's dependencies.

**Closed** 2024-12-19 02:03 UTC
Labels: bug, help wanted, upstream
